name = "TussiWord777"
author = "Marco"
version = "1.3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "027849a422cfd3baf875c9107cb890480ab68ce0a75c046447d300d9803eaf1d"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
