name = "TussiWord777"
author = "Marco"
version = "1.3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2e49d700b71fb7f9db860563e8b62049542b0842812e7b6a99daa42a181f06b"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
