name = "TussiWord777"
author = "Marko"
version = "1.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66f32e652525a6cf2ff9a460f79fc863d87948e3a290aa956ef01c035f349c29"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
